# Generated by Django 4.1.1 on 2022-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_auth', '0002_customusers_is_admin_customusers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
