# Generated by Django 4.0.4 on 2022-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_auth', '0004_remove_customusers_forgot_password_token_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
