# Generated by Django 4.0.4 on 2022-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_auth', '0007_roles_userroles_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
